### ISSUE TITLE
Error json parse

### ISSUE THREAD

**Issue by F474M0R64N4** [JusticeRage/Gepetto#10]
![image](https://user-images.githubusercontent.com/8020186/206334006-849ee3f8-2786-451c-bfc5-d409054a09cb.png)

How to fix? I rename variables 

Can variables be renamed by quantity?

**Comment by JusticeRage** [comment]
Are you using the latest version of the script? 
If you check the commit history, I added a fix for something similar yesterday.

**Comment by JusticeRage** [comment]
You can send the IDB to justicerage at manalyzer dot org, I'll check it out. Please make sure the IDB opens on the function that causes the issue!
Is there more to the error message printed above what you showed in the screenshot? Maybe something like: `Error: couldn't extract a response from davinci-003's output`?

**Comment by F474M0R64N4** [comment]
> 

Answered the email

**Comment by F474M0R64N4** [comment]
@JusticeRage you check my mails?

**Comment by JusticeRage** [comment]
Yes, keep calm, I couldn't work on the project over the week-end.
