### ISSUE TITLE
Why using temperature as 0.6?

### ISSUE THREAD

**Issue by w451** [JusticeRage/Gepetto#11]
Wouldn't using 0 temperature be better because it would create reproducible results and get better accuracy?

**Comment by JusticeRage** [comment]
With a temperature of 0, the responses would be almost deterministic but definitely not more accurate. I think it's preferable to get somewhat random results and having the ability to ask for different ones if the initial ones aren't good enough, than have deterministic ones that you'll be stuck with no matter what.
So I think 0.6, as a default, makes sense, but anyone is welcome to edit the script locally to suit their needs. Maybe at some point I'll create a settings UI where people can store preferences and edit such parameters.
