### ISSUE TITLE
Completing the function information manually

### ISSUE THREAD

**Issue by F474M0R64N4** [JusticeRage/Gepetto#17]
Can you add this?

For example, replace the question by referring to openai

**Comment by JusticeRage** [comment]
Please explain what you mean, I don't get it unfortunately :(

**Comment by F474M0R64N4** [comment]
I mean change query(question) to chatgpt manually

**Comment by F474M0R64N4** [comment]
https://github.com/JusticeRage/Gepetto/blob/main/gepetto.py#L146 window for this question

**Comment by JusticeRage** [comment]
UI-wise, that would be too complex I'm afraid, but you're welcome to try it and submit a PR!
