### ISSUE TITLE
Nothing happen

### ISSUE THREAD

**Issue by reverseXiang** [JusticeRage/Gepetto#21]
why it just output "Request to gpt-3.5-turbo sent..." in the console, and nothing happen. I even dont know why and what happen. Can u give me some advice ?

**Comment by reverseXiang** [comment]
I can use chatgpt onlien

**Comment by JusticeRage** [comment]
Hi! It's difficult to debug the issue like this. Can you share more about what you are doing?
Are there any additional messages in the output window?

**Comment by hzmslx** [comment]
Request to gpt-4 sent...
gpt-4 could not complete the request: <empty message>

**Comment by JusticeRage** [comment]
Nothing more? Unfortunately, it works for me, I just tried it 5 minutes ago. Requests sometimes take a long time to complete but I end up getting results... So I'm afraid you will have to debug the script manually. Please let me know if you do find a bug.

**Comment by adrian-rt** [comment]
doesn't work for me either. I get the following error:

Request to gpt-4 sent...
[INFO] error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False	(util:log_info)
gpt-4 could not complete the request: <empty message>

**Comment by JusticeRage** [comment]
Did you try reading the error message?
Are you sure your API key is valid?

**Comment by reverseXiang** [comment]
I guess it's related to my own network problems. Thanks for your help
