### ISSUE TITLE
turkish locale

### ISSUE THREAD

**Issue by apol3t** [JusticeRage/Gepetto#28]
[tr_TR.zip](https://github.com/JusticeRage/Gepetto/files/12716767/tr_TR.zip)
turkish locale for gepetto

**Comment by JusticeRage** [comment]
Hi! Thanks a lot for the submission! Would you be able to put the translation on Transifex? It makes it easier to manage all languages: https://app.transifex.com/gepetto/gepetto
(Let me know if it doesn't work for one reason or another.)

**Comment by JusticeRage** [comment]
Thanks! I'll include it in the project ASAP!
