### ISSUE TITLE
Update to current openai module version

### ISSUE THREAD

**Issue by melomac** [JusticeRage/Gepetto#30]
Many thanks for sharing Gepetto with the community, and many thanks for adopting GPT-4-turbo so quickly!

I am super excited with AI these days, up to the point I ended up updating openai module to realize Gepetto relies on `openai<1.0` when [current version](https://pypi.org/project/openai/) is 1.2.4.

And it turns out `ChatCompletion` got decommissioned during release 1.0, and this change also breaks your method to load the API key at startup 😬

Would you please be so kind to consider updating the OpenAI code?

**Comment by JusticeRage** [comment]
Thanks for letting me know! I'll work on an update as soon as I have some free time (which may take a couple of weeks...).

**Comment by MamonthPenis** [comment]
Same:
` self._target(*self._args, **self._kwargs)
  File "C:\Program Files/IDA Pro 7.5/plugins\gepetto\models\openai.py", line 40, in query_model
    except openai.InvalidRequestError as e:
AttributeError: module 'openai' has no attribute 'InvalidRequestError`

**Comment by JusticeRage** [comment]
Hi everyone! I've found some time to work on this, things should be resolved now!
Let me know if this works for you, and if it does I'll tag the release.

**Comment by melomac** [comment]
This works just great on a test binary with current IDA Pro with Hex-Rays, current openai (v1.5) and the gpt-4 preview model, many thanks!
