### ISSUE TITLE
I don't now if this a new issu or not 

### ISSUE THREAD

**Issue by mounirthabet** [JusticeRage/Gepetto#35]
Hi, I think I set up everything correctly but this error :/

Request to gpt-3.5-turbo-1106 sent...
gpt-3.5-turbo-1106 could not complete the request: Connection error.
Request to gpt-3.5-turbo-1106 sent...
gpt-3.5-turbo-1106 could not complete the request: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

**Comment by JusticeRage** [comment]
> You exceeded your current quota, please check your plan and billing details.
Check out the error message, I believe the error is that you need to add API credits to your account!
