### ISSUE TITLE
Ollama for Local Models

### ISSUE THREAD

**Issue by mateokladaric** [JusticeRage/Gepetto#36]
Wanted to know if it's any hastle to add compatiblity to Ollama so the model can be run locally.

Haven't tried, just wondering if anyone has.

**Comment by JusticeRage** [comment]
Hi! I could definitely look into this. Is [this ](https://github.com/ollama/ollama) the project you're talking about?

**Comment by mateokladaric** [comment]
Yes, that's it.

**Comment by mateokladaric** [comment]
Most of these projects have their own hosting on localhost, like LM Studio has as well, you could pick the port as well. (not sure if you can with ollama) but they both have like local api endpoints.

Perhaps if I use the OpenAI Proxy you set as a setting to the localhost thing it could function without any alterations.

**Comment by JusticeRage** [comment]
There we are! Please let me know if this works for you!

**Comment by mateokladaric** [comment]
Thank you!!!
