### ISSUE TITLE
Open3

### ISSUE THREAD

**Issue by Log2010643575** [JusticeRage/Gepetto#40]
When I was using Open3, I found that your document and your code did not match. The model written in your document was "gpt-3.5-turbo-1106", but the code you submitted was "gpt-3.5-turbo-0125"

**Comment by JusticeRage** [comment]
Hi! What is Open3 and what "your document" are you referring to?

**Comment by Log2010643575** [comment]
> Hi! What is Open3 and what "your document" are you referring to?
"README.md" document

**Comment by JusticeRage** [comment]
Fixed in bfe67a4bb7ecc444856460cd2638469e9a318438
