### ISSUE TITLE
Every attempt to explain functions or rename variables through our interface leads to an error message.

### ISSUE THREAD

**Issue by cuuemo** [JusticeRage/Gepetto#41]
Problem: Every attempt to explain functions or rename variables through our interface leads to an error message.
Error Message: "Request to gpt-4o sent... General exception encountered while running the query: 'str' object has no attribute 'choices'"

**Comment by JusticeRage** [comment]
Hi, what version of the `openai` python library are you using? Is it up to date?

**Comment by Billy1900** [comment]
> Problem: Every attempt to explain functions or rename variables through our interface leads to an error message. Error Message: "Request to gpt-4o sent... General exception encountered while running the query: 'str' object has no attribute 'choices'"

would you mind giving more erroe message and the backtrace?

**Comment by JusticeRage** [comment]
I'm 99% sure this is due to an outdated `openai` library, please reopen if this is not the case.
