### ISSUE TITLE
Groq: llama-3.1-70b-versatile

### ISSUE THREAD

**Issue by vanhauser-thc** [JusticeRage/Gepetto#42]
Groq has `llama-3.1-70b-versatile` now for some time and with way less rate limiting and token restrictions and better knowledge, so this should be the default --- if it would work. Dunno what the issue is but when I configure that Gepetto receives just nonsenes from Groq.

**Comment by JusticeRage** [comment]
I updated the model but could not reproduce your issue. I tested this on my machine and received perfectly fine data from Groq.
