### ISSUE TITLE
IDA 9.0 doesn't seem to work properly with the CLI

### ISSUE THREAD

**Issue by zhefox** [JusticeRage/Gepetto#44]
![image](https://github.com/user-attachments/assets/9806d956-dbea-4e63-ae65-83b03f8bce58)

![image](https://github.com/user-attachments/assets/dae4a950-b6e5-4bf0-bd6d-eec5785f5d44)

**Comment by JusticeRage** [comment]
I worked on this version with version 9.0 and can confirm that it works, at least on my machine. Is there any error message in the console?

**Comment by zhefox** [comment]
What puzzles me is that I don’t seem to see any errors, and when I modify the name of the menu list module, it doesn’t seem to change it. Then I run the entire plug-in on IDA7.7, and it reports an error.

Failed while executing plugin_t.term():
Traceback (most recent call last):
  File "C:\Users\ZHEFOX\Desktop\IDA\IDA7.7\plugins\gepetto\ida\ui.py", line 136, in term
    self.detach_actions()
  File "C:\Users\ZHEFOX\Desktop\IDA\IDA7.7\plugins\gepetto\ida\ui.py", line 99, in detach_actions
    for model in provider.supported_models():
  File "C:\Users\ZHEFOX\Desktop\IDA\IDA7.7\plugins\gepetto\models\local_ollama.py", line 28, in supported_models
    OLLAMA_MODELS = [m["name"] for m in create_client().list()["models"]]
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ollama\_client.py", line 465, in list
    return self._request('GET', '/api/tags').json()
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ollama\_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError


I'll try test again

**Comment by zhefox** [comment]
C:\Program Files\IDA Professional 9.0\plugins\gepetto.py: Traceback (most recent call last):
  File "C:/Program Files/IDA Professional 9.0/plugins/gepetto.py", line 5, in PLUGIN_ENTRY
    gepetto.config.load_config()  # Loads configuration data from gepetto/config.ini
  File "C:\Users\ZHEFOX\Desktop\IDA\IDA7.7\plugins\gepetto\config.py", line 32, in load_config
    model = instantiate_model(requested_model)
  File "C:\Users\ZHEFOX\Desktop\IDA\IDA7.7\plugins\gepetto\models\model_manager.py", line 27, in instantiate_model
    if model in m.supported_models():
  File "C:\Users\ZHEFOX\Desktop\IDA\IDA7.7\plugins\gepetto\models\local_ollama.py", line 28, in supported_models
    OLLAMA_MODELS = [m["name"] for m in create_client().list()["models"]]
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ollama\_client.py", line 465, in list
    return self._request('GET', '/api/tags').json()
  File "C:\Users\ZHEFOX\AppData\Local\Programs\Python\Python310\lib\site-packages\ollama\_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError


In IDA 9.0，It seems that this error also exists. Since I installed the ollama library, if not, it will report that the module is missing.

**Comment by zhefox** [comment]
Does it have any cache files, which caused me to continue to use the old version of gepetto? According to the above error report, I can see that I am obviously running in IDA9.0, but he accessed the plug-in directory of IDA7.7

Now there are errors. It seems that the old version of the plug-in in the 7.7 directory has been used by default, so there are no errors. My code has been updated and has not been modified simultaneously. The error content is the same as above.

**Comment by zhefox** [comment]
This is a small problem. Just determine whether the .ini setting is empty, and then determine whether to return the model content.

**Comment by JusticeRage** [comment]
I'm sorry, the Chinese part of your post is not clear for me (I don't speak the language).
Can you clarify which missing setting caused the exception?

**Comment by zhefox** [comment]
When using the plug-in, it enabled ollama by default. Because I did not deploy ollama, try except reported an error, but the captured type does not contain the client's responseError, so the error message will be displayed

fixed:
`
    @staticmethod
    def supported_models():
        global OLLAMA_MODELS

        if OLLAMA_MODELS is None:
            try:
                OLLAMA_MODELS = [m["name"] for m in create_client().list()["models"]]
            except _httpx.ConnectError:
                OLLAMA_MODELS = []
            except ollama._types.ResponseError:  # catch ResponseError
                OLLAMA_MODELS = []
        return OLLAMA_MODELS
`

**Comment by JusticeRage** [comment]
This is weird. Which version of the `ollama` package for Python are you using?
I tested the script on a machine without Ollama and it didn't cause this exception.

**Comment by JusticeRage** [comment]
Hello, please check the output windows for any error message. The plug-in won't show up if no LLM is provided.

**Comment by Kyxyzzy** [comment]
> Hello, please check the output windows for any error message. The plug-in won't show up if no LLM is provided.

So the output is looking fine, no errors. here is my config. I am a bit unsure how to configure it for using LMstudio with a local lm. 

This is currently my config.ini

"[Gepetto]
MODEL = qwq-32b

# Specify the program language. It can be "fr_FR", "zh_CN", or any folder in locales. Defaults to English.
LANGUAGE = 

# Base URL if you want to redirect requests to a different / local model.
# Custom for LMstudio
# Leave blank unless you know what you are doing :)
BASE_URL = http://127.0.0.1:1234
"
