### ISSUE TITLE
Rename variables doesn't work

### ISSUE THREAD

**Issue by melomac** [JusticeRage/Gepetto#45]
On IDA Pro 8.4 SP2 or IDA Pro 9 beta 4, starting with commit `fbbae19d4e593193b954e1dc8de6305da63014d2`, the `Rename variable` feature no longer works.

Step to repro:
- open a target
- choose a function
- display HR pseudocode
- right click Gepetto / Rename variables: `Request to gpt-4o sent...`

Starting with commit `fbbae19d4e593193b954e1dc8de6305da63014d2`, this no longer works. Checking out previous commit `59dbf471eaac9cea3df612c2dcb77781234249dc` restore the feature.

Explain function works fine.

**Comment by JusticeRage** [comment]
A pesky indentation problem 🤦‍♂️
Thanks a lot for reporting!
