### ISSUE TITLE
No matching distribution found for openai>=1.0.0

### ISSUE THREAD

**Issue by ClonkAndre** [JusticeRage/Gepetto#50]
When trying to install the required modules via the "requirements.txt" file, i'm getting this error printed in the command prompt:

"
ERROR: Could not find a version that satisfies the requirement openai>=1.0.0 (from versions: 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5)

Error: No matching distribution found for openai>=1.0.0
"

The same goes for the "together" and "ollama" module.

I never really did anything with python before, so i'm not quite sure what's going on. Any help would be appreciated!

**Comment by JusticeRage** [comment]
Hi, which version of Python are you using? I'd like to make sure you're on Python 3 and not Python 2 first.

**Comment by ClonkAndre** [comment]
Hey, thanks for the quick response! I'm on Python 3.7.0.

**Comment by JusticeRage** [comment]
The `openai` package requires Python 3.8+ ([source](https://pypi.org/project/openai/)).
That's most likely your issue, try upgrading Python.

**Comment by JusticeRage** [comment]
The line that causes an error uses syntax used in Python 3.9 (released in October 2020). Please try using at least that.
